[2024-12-23T10:10:55.838+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-12-23T10:10:55.853+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_etl_workflow.movie_json_to_csv scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T10:10:55.868+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_etl_workflow.movie_json_to_csv scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T10:10:55.869+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-12-23T10:10:55.891+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): movie_json_to_csv> on 2024-12-22 00:00:00+00:00
[2024-12-23T10:10:55.896+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2024-12-23T10:10:55.900+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_etl_workflow', 'movie_json_to_csv', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmp66q0bf4x']
[2024-12-23T10:10:55.902+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask movie_json_to_csv
[2024-12-23T10:10:55.925+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T10:10:55.988+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_etl_workflow.movie_json_to_csv scheduled__2024-12-22T00:00:00+00:00 [running]> on host 706f06857b2f
[2024-12-23T10:10:56.014+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-12-23T10:10:56.094+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_etl_workflow' AIRFLOW_CTX_TASK_ID='movie_json_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T10:10:56.096+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T10:10:56.097+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py']
[2024-12-23T10:10:56.108+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T10:10:56.318+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-23T10:10:56.319+0000] {subprocess.py:93} INFO -   File "/opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py", line 8, in <module>
[2024-12-23T10:10:56.319+0000] {subprocess.py:93} INFO -     movies = json.load(json_file)
[2024-12-23T10:10:56.320+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
[2024-12-23T10:10:56.320+0000] {subprocess.py:93} INFO -     return loads(fp.read(),
[2024-12-23T10:10:56.321+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
[2024-12-23T10:10:56.321+0000] {subprocess.py:93} INFO -     return _default_decoder.decode(s)
[2024-12-23T10:10:56.321+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
[2024-12-23T10:10:56.322+0000] {subprocess.py:93} INFO -     raise JSONDecodeError("Extra data", s, end)
[2024-12-23T10:10:56.322+0000] {subprocess.py:93} INFO - json.decoder.JSONDecodeError: Extra data: line 202825 column 3 (char 7563840)
[2024-12-23T10:10:56.345+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-23T10:10:56.362+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-23T10:10:56.369+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=movie_etl_workflow, task_id=movie_json_to_csv, execution_date=20241222T000000, start_date=20241223T101055, end_date=20241223T101056
[2024-12-23T10:10:56.383+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 66 for task movie_json_to_csv (Bash command failed. The command returned a non-zero exit code 1.; 86)
[2024-12-23T10:10:56.406+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-23T10:10:56.433+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
