[2025-01-17T07:37:41.222+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2025-01-17T07:37:40.184668+00:00 [queued]>
[2025-01-17T07:37:41.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2025-01-17T07:37:40.184668+00:00 [queued]>
[2025-01-17T07:37:41.242+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-01-17T07:37:41.262+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_rating_data> on 2025-01-17 07:37:40.184668+00:00
[2025-01-17T07:37:41.268+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2025-01-17T07:37:41.272+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_etl_workflow', 'fetch_rating_data', 'manual__2025-01-17T07:37:40.184668+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmphxuu5une']
[2025-01-17T07:37:41.273+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask fetch_rating_data
[2025-01-17T07:37:41.295+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-17T07:37:41.343+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2025-01-17T07:37:40.184668+00:00 [running]> on host 1d5d3d5ac065
[2025-01-17T07:37:41.455+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_etl_workflow' AIRFLOW_CTX_TASK_ID='fetch_rating_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T07:37:40.184668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T07:37:40.184668+00:00'
[2025-01-17T07:37:41.459+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T07:37:41.460+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_rating_Themoviedb.py']
[2025-01-17T07:37:41.476+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T07:38:47.225+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-01-17T07:38:47.237+0000] {process_utils.py:131} INFO - Sending 15 to group 65. PIDs of all processes in the group: [68, 65]
[2025-01-17T07:38:47.239+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 65
[2025-01-17T07:38:47.241+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-17T07:38:47.244+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-17T07:38:47.341+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=65, status='terminated', exitcode=0, started='07:37:40') (65) terminated with exit code 0
[2025-01-17T07:38:47.346+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=68, status='terminated', started='07:37:40') (68) terminated with exit code None
